# Generated by Django 4.2.2 on 2023-07-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productbuyed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBuyed',
        ),
    ]
