# Generated by Django 4.2.2 on 2023-07-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'permissions': [('staff_view_product', 'Can view staff product'), ('staff_change_product', 'Can change staff product'), ('staff_delete_product', 'Can delete staff product')]},
        ),
    ]
