# Generated by Django 4.2.2 on 2023-07-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('staff_add_category', 'OLP staff add category'), ('staff_view_category', 'OLP staff view category'), ('staff_change_category', 'OLP staff change category'), ('staff_delete_category', 'OLP staff delete category')], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='handle',
            options={'permissions': [('staff_add_handle', 'OLP staff add handle'), ('staff_view_handle', 'OLP staff view handle'), ('staff_change_handle', 'OLP staff change handle'), ('staff_delete_handle', 'OLP staff delete handle')], 'verbose_name_plural': 'Empuñaduras'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'permissions': [('staff_add_message', 'OLP staff add message'), ('staff_view_message', 'OLP staff view message'), ('staff_change_message', 'OLP staff change message'), ('staff_delete_message', 'OLP staff delete message')], 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='prod_secimg',
            options={'permissions': [('staff_add_prod_secimg', 'OLP staff add prod_secimg'), ('staff_view_prod_secimg', 'OLP staff view prod_secimg'), ('staff_change_prod_secimg', 'OLP staff change prod_secimg'), ('staff_delete_prod_secimg', 'OLP staff delete prod_secimg')], 'verbose_name_plural': 'Imagenes Secundarias de Productos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'permissions': [('staff_add_product', 'OLP staff add product'), ('staff_view_product', 'OLP staff view product'), ('staff_change_product', 'OLP staff change product'), ('staff_delete_product', 'OLP staff delete product')], 'verbose_name_plural': 'Productos'},
        ),
    ]
