# Generated by Django 4.2.2 on 2023-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=450, null=True, verbose_name='Descripción'),
        ),
    ]
