# Generated by Django 4.2.2 on 2023-08-07 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 16, 6, 44, 159173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Hay Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blade_size',
            field=models.CharField(default='__ x __ x __ mm', max_length=50, verbose_name='Tamaño de la hoja en mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='handle_size',
            field=models.CharField(default='__ x __ x __ mm', max_length=50, verbose_name='Tamaño de la empuñadura en mm'),
        ),
    ]
