# Generated by Django 4.2.2 on 2023-08-07 22:20

import datetime
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_publish_date_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=product.models.CategoryNameField(max_length=70, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='material',
            field=product.models.HandleMaterialField(max_length=100, unique=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=product.models.ProdNameField(max_length=100, unique=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 22, 20, 9, 629818, tzinfo=datetime.timezone.utc)),
        ),
    ]
