# Generated by Django 4.2.2 on 2024-02-09 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_category_name_alter_handle_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 21, 19, 37, 704132, tzinfo=datetime.timezone.utc)),
        ),
    ]
