# Generated by Django 4.2.2 on 2023-07-07 23:24

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10, validators=[payment.models.validate_address_num])),
                ('zipcode', models.CharField(max_length=10, validators=[payment.models.validate_address_num])),
                ('address_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment')], max_length=10)),
                ('apartment_flor', models.CharField(blank=True, max_length=4, null=True)),
                ('apartment_id', models.CharField(blank=True, max_length=4, null=True)),
                ('special_instructions', models.CharField(blank=True, max_length=250, null=True)),
                ('choosen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['owner', '-choosen_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=150, null=True)),
                ('preference_id', models.CharField(max_length=151, null=True)),
                ('pay_method', models.CharField(max_length=100, null=True)),
                ('shipping_method', models.CharField(max_length=50, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
            ],
        ),
    ]
