# Generated by Django 4.2.2 on 2023-07-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
