# Generated by Django 4.2.2 on 2023-07-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preference_id',
        ),
        migrations.AddField(
            model_name='order',
            name='products_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
