# Generated by Django 4.2.2 on 2023-07-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_order_customer_id_remove_order_preference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('expirate_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('type_id', models.CharField(choices=[('1', 'DNI'), ('2', 'CPF'), ('3', 'SSN')], max_length=4)),
                ('number_id', models.CharField(max_length=20)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('status_returned', models.CharField(choices=[('Apro', 'approved'), ('Pend', 'pending'), ('Deni', 'denied')], max_length=10)),
            ],
        ),
    ]
