# Generated by Django 4.2.2 on 2023-07-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='issuer',
            field=models.CharField(choices=[('visa', 'visa'), ('mastercard', 'mastercard'), ('american express', 'american express')], default='visa', max_length=20),
            preserve_default=False,
        ),
    ]
