# Generated by Django 4.2.2 on 2023-07-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_card_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type_card',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='credit', max_length=7),
            preserve_default=False,
        ),
    ]
