# Generated by Django 4.2.2 on 2023-07-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_carduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='carduser',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
