# Generated by Django 4.2.2 on 2023-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_carduser_update_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carduser',
            options={'ordering': ['-update_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='paymethod_cash_type',
            field=models.CharField(blank=True, choices=[('pagofacil', 'pagofacil'), ('rapipago', 'rapipago'), ('wu', 'wu')], max_length=10, null=True),
        ),
    ]
