# Generated by Django 4.2.2 on 2023-07-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_carduser_options_order_paymethod_cash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.carduser'),
        ),
    ]
