# Generated by Django 4.2.2 on 2023-07-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_order_pay_method_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount_percentage', models.BooleanField(default=False)),
                ('discount_shipping', models.BooleanField(default=False)),
                ('discount', models.CharField(blank=True, max_length=5, null=True)),
                ('enabled_from', models.DateField()),
                ('enabled_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.discountcode'),
        ),
    ]
