# Generated by Django 4.2.2 on 2023-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_discountcode_order_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymethod_cash_type',
            field=models.CharField(blank=True, choices=[('pagofacil', 'pagofacil'), ('rapipago', 'rapipago'), ('western union', 'western union')], max_length=17, null=True),
        ),
    ]
