# Generated by Django 4.2.2 on 2023-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_order_paymethod_cash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emition_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
