# Generated by Django 4.2.2 on 2023-07-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_order_emition_date_order_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(null=True),
        ),
    ]
