# Generated by Django 4.2.2 on 2023-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymethod_cash_type',
            field=models.CharField(blank=True, choices=[('paypal', 'paypal'), ('mercadopago', 'mercadopago'), ('brubank', 'brubank')], max_length=15, null=True),
        ),
    ]
