# Generated by Django 4.2.2 on 2023-07-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_order_paymethod_wallet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_arrives',
            field=models.DateField(blank=True, null=True),
        ),
    ]
