# Generated by Django 4.2.2 on 2023-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_rename_emition_date_order_emition_cash_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status_returned',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], max_length=10),
        ),
    ]
