# Generated by Django 4.2.2 on 2023-07-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_cartitems_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('payment', '0028_discountcode_add_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['owner', '-choosen_at'], 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name_plural': 'Codigo de Descuento'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='productbuyed',
            options={'verbose_name_plural': 'Productos comprados'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment')], max_length=10, verbose_name='Tipo de domicilio'),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_flor',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Piso del apartamento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_id',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Identificador del apartamento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, validators=[payment.models.validate_address_num], verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region/Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Indicaciones extras'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=150, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=10, validators=[payment.models.validate_address_num], verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='add_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.BooleanField(default=False, verbose_name='Descuento en porcentage?'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_shipping',
            field=models.BooleanField(default=False, verbose_name='Descuento en envio?'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='enabled_from',
            field=models.DateField(verbose_name='Disponible desde'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='enabled_to',
            field=models.DateField(verbose_name='Disponible hasta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.address', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False, verbose_name='Pagado?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(null=True, verbose_name='Monto de descontado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.discountcode', verbose_name='Codigo de descuento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='emition_cash_date',
            field=models.DateTimeField(null=True, verbose_name='Emision de pago en efectivo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_cash_date',
            field=models.DateTimeField(null=True, verbose_name='Expiración de pago en efectivo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='payment.OrderItem', to='product.product', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(max_length=100, null=True, verbose_name='Precio de Productos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.carduser', verbose_name='Tarjeta usada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymethod_cash_type',
            field=models.CharField(blank=True, choices=[('pagofacil', 'pagofacil'), ('rapipago', 'rapipago'), ('western union', 'western union')], max_length=17, null=True, verbose_name='Metodo pago en efectivo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymethod_wallet_type',
            field=models.CharField(blank=True, choices=[('paypal', 'paypal'), ('mercadopago', 'mercadopago'), ('brubank', 'brubank')], max_length=15, null=True, verbose_name='Metodo Billetera virtual'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products_price',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_arrives',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de arribo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(max_length=50, null=True, verbose_name='Metodo de envio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio de envio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('expired', 'expired'), ('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], default='incomplete', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total a pagar'),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='buyed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comprado por'),
        ),
    ]
