# Generated by Django 4.2.2 on 2023-07-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_alter_address_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'permissions': [('staff_add_discountcode', 'OLP staff add discountcode'), ('staff_view_discountcode', 'OLP staff view discountcode'), ('staff_change_discountcode', 'OLP staff change discountcode'), ('staff_delete_discountcode', 'OLP staff delete discountcode')], 'verbose_name_plural': 'Codigo de Descuento'},
        ),
        migrations.AlterModelOptions(
            name='productbuyed',
            options={'permissions': [('staff_add_productbuyed', 'OLP staff add productbuyed'), ('staff_view_productbuyed', 'OLP staff view productbuyed'), ('staff_change_productbuyed', 'OLP staff change productbuyed'), ('staff_delete_productbuyed', 'OLP staff delete productbuyed')], 'verbose_name_plural': 'Productos comprados'},
        ),
    ]
