# Generated by Django 4.2.2 on 2023-08-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_alter_discountcode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='carduser',
            options={'ordering': ['-update_date'], 'verbose_name_plural': 'Tarjetas por usuario'},
        ),
    ]
