# Generated by Django 4.2.2 on 2023-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_alter_card_options_alter_carduser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.IntegerField(max_length=3, verbose_name='Descuento'),
        ),
    ]
