# Generated by Django 4.2.2 on 2023-08-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_alter_discountcode_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.IntegerField(verbose_name='Descuento'),
        ),
    ]
