# Generated by Django 4.2.2 on 2023-08-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_alter_discountcode_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_shipping',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_kind',
            field=models.CharField(choices=[('Total', 'Total'), ('Shipping', 'Shipping')], default='Total', max_length=9),
            preserve_default=False,
        ),
    ]
