# Generated by Django 4.2.2 on 2023-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_remove_discountcode_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_received_date',
            field=models.DateTimeField(null=True),
        ),
    ]
