# Generated by Django 4.2.2 on 2023-08-07 22:20

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_order_pay_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=payment.models.CodeNameField(max_length=15, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='productbuyed',
            name='buyed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra'),
        ),
    ]
